MAYOR EQU 0x21
MENOR EQU 0x22
ENTRADA	EQU 0X23

INICIO
	ORG 0x00
	GOTO START

START
	BSF	STATUS,5 ; PONE UN 1 EN STATUS BIT 5, PARA MOVERNOS AL BANCO 1 
	CLRF	TRISD ; PONE EN 0 TRISB Y LA BANDERA Z
	MOVLW	B'00001111' ; PONEMOS EN BINARIO LAS ENTRADAS QUE QUEREMOS HABILITAR PIN 0 AL 3 ENTRADA DE DIGITOS Y PIN 5 MOSTRAR DIGITO
	MOVWF	TRISC ;MUEVE LO QUE TENGAMOS EN W HACIA TRISC PARA HABILITAR LAS ENTRADAS
	CLRW	;LIMPIAR W
	BCF	STATUS, 5 ; PONE UN 0 EN STATUS EN BIT 5 Y ESTO NOS MUEVE AL BANCO 0	
	
	MOVLW 	B'00000101'
	MOVWF	MAYOR
	MOVLW 	B'00000001'
	MOVWF	MENOR
	GOTO 	LEER;

LEER
	;MOVF	PORTC,W ; MUEVE LO DEL PUERTO A C A W
	MOVLW	B'00000000'
	MOVWF	ENTRADA
	GOTO 	COMPARACION

COMPARACION	
	MOVF	ENTRADA,W
	SUBWF	MENOR,W	
	BTFSC	STATUS,C
	GOTO	EntradaMenor

	MOVF	ENTRADA,W
	SUBWF	MAYOR,W
	BTFSS	STATUS,C
	GOTO 	EntradaMayor

	GOTO	LEER

EntradaMayor
	MOVF	ENTRADA,W
	MOVWF	MAYOR
	MOVLW	B'00000001'
	MOVWF	PORTD
	GOTO 	LEER

EntradaMenor
	MOVF	ENTRADA,W
	MOVWF	MENOR
	MOVLW	B'00000010'
	MOVWF	PORTD
	GOTO 	LEER