Mayor_Encontrado EQU 0x21
Menor_Encontrado EQU 0x22
ENTRADA_Comp	EQU 0X23

INICIO
	ORG 0x00
	GOTO START

START
	BSF	STATUS,5 ; PONE UN 1 EN STATUS BIT 5, PARA MOVERNOS AL BANCO 1 
	CLRF	TRISD ; PONE EN 0 TRISB Y LA BANDERA Z
	MOVLW	B'00001111' ; PONEMOS EN BINARIO LAS ENTRADA_CompS QUE QUEREMOS HABILITAR PIN 0 AL 3 ENTRADA_Comp DE DIGITOS Y PIN 5 MOSTRAR DIGITO
	MOVWF	TRISC ;MUEVE LO QUE TENGAMOS EN W HACIA TRISC PARA HABILITAR LAS ENTRADA_CompS
	CLRW	;LIMPIAR W
	BCF	STATUS, 5 ; PONE UN 0 EN STATUS EN BIT 5 Y ESTO NOS MUEVE AL BANCO 0	
	
	MOVLW 	B'00000101'
	MOVWF	Mayor_Encontrado
	MOVLW 	B'00000001'
	MOVWF	Menor_Encontrado
	GOTO 	LEER;

LEER
	;MOVF	PORTC,W ; MUEVE LO DEL PUERTO A C A W
	MOVLW	B'00000000'
	MOVWF	ENTRADA_Comp
	GOTO 	Comparacion_nums

Comparacion_nums	
	MOVF	ENTRADA_Comp,W
	SUBWF	Menor_Encontrado,W	
	BTFSC	STATUS,C
	CALL	EntradaMenor_nums

	MOVF	ENTRADA_Comp,W
	SUBWF	Mayor_Encontrado,W
	BTFSS	STATUS,C
	CALL 	EntradaMayor_nums

	RETURN

EntradaMayor_nums
	MOVF	ENTRADA_Comp,W
	MOVWF	Mayor_Encontrado
	MOVLW	B'00000001'
	MOVWF	PORTD
	RETURN

EntradaMenor_nums
	MOVF	ENTRADA_Comp,W
	MOVWF	Menor_Encontrado
	MOVLW	B'00000010'
	MOVWF	PORTD
	RETURN