DATO EQU 0X21; CREAMOS UNA VARIABLE EN BANCO 0 EN AREA DE MEMORIA DE PROPOSITO GENERAL
INICIO
	ORG 0X00
	GOTO START

START
;CONFIGURACION DE ENTRADAS EN C Y SALIDAS EN B
	BSF	STATUS,5 ; PONE UN 1 EN STATUS BIT 5, PARA MOVERNOS AL BANCO 1 
	CLRF	TRISB ; PONE EN 0 TRISB Y LA BANDERA Z
	MOVLW	B'00101111' ; PONEMOS EN BINARIO LAS ENTRADAS QUE QUEREMOS HABILITAR PIN 0 AL 3 ENTRADA DE DIGITOS Y PIN 5 MOSTRAR DIGITO
	MOVWF	TRISC ;MUEVE LO QUE TENGAMOS EN W HACIA TRISC PARA HABILITAR LAS ENTRADAS
	CLRW	;LIMPIAR W
	BCF	STATUS, 5 ; PONE UN 0 EN STATUS EN BIT 5 Y ESTO NOS MUEVE AL BANCO 0	

	GOTO 	LEER;

LEER
;LEMOS EL DATO INGRESADO EN PUERTO C
	MOVF	PORTC, W ;MUEVE LA ENTRADA DEL PUERTO C HACIA W
	MOVWF	DATO 	;MUEVE DE W A LA VARIABLE DATO
	GOTO	COMPARACION 

COMPARACION
;COMPARACION BIT POR BIT 
	MOVLW	B'00100000' ;LE ENVIAMOS A W EL NUMERO 0 EN BINARIO EN 8 BITS
	SUBWF	DATO,W 	;LE VAMOS A QUITAR A DATO W (DATO-W)=W
	BTFSC	STATUS,Z
	GOTO	MOSTRAR0

	MOVLW	B'00100001' ;LE ENVIAMOS A W EL NUMERO 1 EN BINARIO EN 8 BITS
	SUBWF	DATO,W 	;LE VAMOS A QUITAR A DATO W (DATO-W)=W
	BTFSC	STATUS,Z
	GOTO	MOSTRAR1

	MOVLW	B'00100010' ;LE ENVIAMOS A W EL NUMERO 2 EN BINARIO EN 8 BITS
	SUBWF	DATO,W 	;LE VAMOS A QUITAR A DATO W (DATO-W)=W
	BTFSC	STATUS,Z
	GOTO	MOSTRAR2
	
	MOVLW	B'00100011' ;LE ENVIAMOS A W EL NUMERO 3 EN BINARIO EN 8 BITS
	SUBWF	DATO,W 	;LE VAMOS A QUITAR A DATO W (DATO-W)=W
	BTFSC	STATUS,Z
	GOTO	MOSTRAR3

	MOVLW	B'00100100' ;LE ENVIAMOS A W EL NUMERO 4 EN BINARIO EN 8 BITS
	SUBWF	DATO,W 	;LE VAMOS A QUITAR A DATO W (DATO-W)=W
	BTFSC	STATUS,Z
	GOTO	MOSTRAR4

	MOVLW	B'00100101' ;LE ENVIAMOS A W EL NUMERO 5 EN BINARIO EN 8 BITS
	SUBWF	DATO,W 	;LE VAMOS A QUITAR A DATO W (DATO-W)=W
	BTFSC	STATUS,Z
	GOTO	MOSTRAR5

	MOVLW	B'00100110' ;LE ENVIAMOS A W EL NUMERO 6 EN BINARIO EN 8 BITS
	SUBWF	DATO,W 	;LE VAMOS A QUITAR A DATO W (DATO-W)=W
	BTFSC	STATUS,Z
	GOTO	MOSTRAR6

	MOVLW	B'00100111' ;LE ENVIAMOS A W EL NUMERO 7 EN BINARIO EN 8 BITS
	SUBWF	DATO,W 	;LE VAMOS A QUITAR A DATO W (DATO-W)=W
	BTFSC	STATUS,Z
	GOTO	MOSTRAR7

	MOVLW	B'00101000' ;LE ENVIAMOS A W EL NUMERO 8 EN BINARIO EN 8 BITS
	SUBWF	DATO,W 	;LE VAMOS A QUITAR A DATO W (DATO-W)=W
	BTFSC	STATUS,Z
	GOTO	MOSTRAR8

	MOVLW	B'00101001' ;LE ENVIAMOS A W EL NUMERO 9 EN BINARIO EN 8 BITS
	SUBWF	DATO,W 	;LE VAMOS A QUITAR A DATO W (DATO-W)=W
	BTFSC	STATUS,Z
	GOTO	MOSTRAR9
	
	MOVLW	B'00000000'
	MOVWF	PORTB
	GOTO	LEER

MOSTRAR0
	MOVLW B'00111111' ; EN BINARIO PONEMOS 0 LOS NECESARIOS PARA PREDER EL DISPLAY EN 0
	MOVWF PORTB	;MOVEMOS LOS BINARIOS A PORT B 
	GOTO LEER

MOSTRAR1
	MOVLW B'00000110' ; EN BINARIO PONEMOS 1 LOS NECESARIOS PARA PREDER EL DISPLAY EN 0
	MOVWF PORTB	;MOVEMOS LOS BINARIOS A PORT B 
	GOTO LEER

MOSTRAR2
	MOVLW B'01011011' ; EN BINARIO PONEMOS 2 LOS NECESARIOS PARA PREDER EL DISPLAY EN 0
	MOVWF PORTB	;MOVEMOS LOS BINARIOS A PORT B 
	GOTO LEER

MOSTRAR3
	MOVLW B'01001111' ; EN BINARIO PONEMOS 3 LOS NECESARIOS PARA PREDER EL DISPLAY EN 0
	MOVWF PORTB	;MOVEMOS LOS BINARIOS A PORT B 
	GOTO LEER
		
MOSTRAR4
	MOVLW B'01100110' ; EN BINARIO PONEMOS 4 LOS NECESARIOS PARA PREDER EL DISPLAY EN 0
	MOVWF PORTB	;MOVEMOS LOS BINARIOS A PORT B 
	GOTO LEER

MOSTRAR5
	MOVLW B'01101101' ; EN BINARIO PONEMOS 5 LOS NECESARIOS PARA PREDER EL DISPLAY EN 0
	MOVWF PORTB	;MOVEMOS LOS BINARIOS A PORT B 
	GOTO LEER

MOSTRAR6
	MOVLW B'01111101' ; EN BINARIO PONEMOS 6 LOS NECESARIOS PARA PREDER EL DISPLAY EN 0
	MOVWF PORTB	;MOVEMOS LOS BINARIOS A PORT B 
	GOTO LEER

MOSTRAR7
	MOVLW B'00000111' ; EN BINARIO PONEMOS 7 LOS NECESARIOS PARA PREDER EL DISPLAY EN 0
	MOVWF PORTB	;MOVEMOS LOS BINARIOS A PORT B 
	GOTO LEER

MOSTRAR8
	MOVLW B'01111111' ; EN BINARIO PONEMOS 8 LOS NECESARIOS PARA PREDER EL DISPLAY EN 0
	MOVWF PORTB	;MOVEMOS LOS BINARIOS A PORT B 
	GOTO LEER

MOSTRAR9
	MOVLW B'01100111' ; EN BINARIO PONEMOS 9 LOS NECESARIOS PARA PREDER EL DISPLAY EN 0
	MOVWF PORTB	;MOVEMOS LOS BINARIOS A PORT B 
	GOTO LEER